version: '3.8'

services:
  django:
    build:
      context: ../../build_image
      dockerfile: ./debug/Dockerfile

    ports:
      - "8001:8000"
      - "5678:5678"
    volumes:
      - ../../../app/:/app/
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
