services:
  django:
    image: '${RECIPES_IMAGE_NAME}'

    ports:
      - "8001:8000"
      - "5678:5678"
    volumes:
      - ../../../app/:/app/
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:14.15-alpine3.21
    environment:
      POSTGRES_DB: recipes_book
      POSTGRES_USER: gsu
      POSTGRES_PASSWORD: gsu
    ports:
      - "4532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: